{{- if .Values.frontend.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-frontend
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    app: {{ include "chart.fullname" . }}-frontend
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "chart.selectorLabels" . | nindent 4 }}
    app: {{ include "chart.fullname" . }}-frontend
  ports:
    - protocol: TCP
      port: {{ .Values.frontend.port }}
      targetPort: 80
{{- end -}}