apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: mongodb
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 3940
      targetPort: 27017
  selector:
    app.kubernetes.io/name: mongodb
    app.kubernetes.io/instance: {{ .Release.Name }}