apiVersion: v1
kind: Secret
metadata:
  name: mongodb
  labels:
    app.kubernetes.io/component: mongodb
    {{- include "chart.labels" . | nindent 4 }}
type: Opaque
data:
  mongodb-root-password: {{ randAlphaNum 10 | b64enc | quote }}
  mongodb-password: {{ randAlphaNum 10 | b64enc | quote }}